<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Notification.Application\Handlers\" />
    <Folder Include="Notification.Application\MappingProfiles\" />
    <Folder Include="Notification.Domain\IUnitOfWork\" />
    <Folder Include="Notification.Infrastructure\Configration\" />
    <Folder Include="Notification.Infrastructure\UnitOfWork\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManager.SharedLayer\TaskManager.SharedLayer.csproj" />
  </ItemGroup>

</Project>
